title: Sarah Mohr
url: "https://smmohr.github.io"
baseurl: "/"

markdown: kramdown
ins_logo: "logo.png"
favicon_location: "logo.png"

tracking_id: #

footer: yes
# footer_url: "#"
footer_text: "Copyright © 2024 Sarah Mohr"


sass:
    style: compressed
    sass_dir: _sass

nav:
 # - name: "Home"
 #   link: "/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "CV"
   link: "cv.pdf"
 # - name: "Contact"
 #   link: "contact"

