title: Sarah Mohr - Neuroscientist, Researcher, and Squirrels
url: "https://smmohr.github.io"
baseurl: "/"

author: Sarah Mohr
description: Neuroscientist, Researcher, and Squirrels

markdown: kramdown
ins_logo: "logo.png"

favicon: yes
favicon_location: "favicon.ico?"

tracking_id: #

footer: yes
footer_url: no
footer_url_link: "#"
footer_text: "Copyright © 2024 Sarah Mohr"


sass:
    style: compressed
    sass_dir: _sass

nav:
 # - name: "Home"
 #   link: "/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "CV"
   link: "cv.pdf"
 # - name: "Contact"
 #   link: "contact"

